services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - APP_PORT=${APP_PORT:-8080}